name: golangci-lint
on: push

jobs:
  makefile:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Build Docker Images, Test, and Format
        run: make build-docker-images

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Run tests using Make
        run: make test

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Setup Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Format code using Make
        run: make format
